export const MAX_ROUND = 10;
export const MAX_TIME_PER_ROUND_SEC = 600;
export const SHOWING_GUESSED_RESULT_MILLISECCOND = 3000;
export const SPLASH_PAGE_SHOWING_MILLISECOND = 300000000;

/** Screen sizes */
export const MOBILE_MAX_SCREEN_SIZE = 600;
export const MIDDLE_MAX_SCREEN_SIZE = 960;